### ISSUE TITLE
1.17.1 Sugarcane 服务端无法加载插件

### ISSUE THREAD

**Issue by AlexXuCN** [MeowCat-Studio/kato-message-source#5]
[Sugarcane](https://github.com/SugarcaneMC/Sugarcane) 是某个高版本/高性能的paper fork
我在使用这个服务端并尝试加载bmf.jar (release的1.0.0版本) 时出现以下报错
```
[19:31:37 ERROR]: Could not load 'plugins/bmf.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:405) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:296) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at net.minecraft.server.MinecraftServer$$Lambda$3677/0x00000000bc3f8550.run(Unknown Source) ~[app:?]
        at java.lang.Thread.run(Thread.java:853) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.J9VMInternals.ensureError(J9VMInternals.java:184) ~[?:?]
        at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:173) ~[?:?]
        at java.lang.Class.forNameImpl(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:420) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        ... 8 more
Caused by: java.lang.IllegalStateException: Cannot get plugin for class org.meowcat.taboolib.common.env.DependencyDownloader from a static initializer
        at org.bukkit.plugin.java.JavaPlugin.getProvidingPlugin(JavaPlugin.java:425) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at io.papermc.paper.logging.SysoutCatcher$WrappedOutStream.println(SysoutCatcher.java:35) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at org.meowcat.taboolib.common.env.DependencyDownloader.injectClasspath(DependencyDownloader.java:106) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:251) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:302) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:347) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:330) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:177) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:249) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:302) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:347) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.DependencyDownloader.download(DependencyDownloader.java:330) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.RuntimeEnv.loadDependency(RuntimeEnv.java:132) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.env.RuntimeEnv.setup(RuntimeEnv.java:41) ~[bmf.jar:?]
        at org.meowcat.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:60) ~[bmf.jar:?]
        at org.meowcat.taboolib.platform.BukkitPlugin.<clinit>(BukkitPlugin.java:34) ~[bmf.jar:?]
        at java.lang.Class.forNameImpl(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:420) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:73) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[patched_1.17.1.jar:git-Sugarcane-1.17.1/dev-45]
        ... 8 more
```
不知道是什么原因awa

**Comment by AlexXuCN** [comment]
服务器插件列表:   
```
> plugins
[19:55:11 INFO]: Plugins (20): AuthMe, floodgate, FloodgatePlaceholders, Geyser-Spigot, JukeBox, LuckPerms, Multiverse-Core, Multiverse-Portals, NoteBlockAPI, PlaceholderAPI, ProtocolLib, Slimefun, Terra, Themis, UltiCore, UltiEconomy, UltimateTimber, UltiTools, Vault, WorldEdit
```
---
而且我看Taboolib那边说  

TabooLib 自 `6.0` 版本起不再是 动态下载 模式，而是改为由依赖插件自行打包并随本体同时载入的纯类库形式。这极大程度的提升了插件的稳定性和安全性，正因如此 TabooLib 的所有工具也在这个版本进行了全面重新设计。整个库被拆分为数个模块，由这些模块共同组成 TabooLib 6.0，你可以在 [这里](https://docs.tabooproject.org/about/structure.html) 了解模块之间的结构与相关信息，或直接访问我们的 [Github](https://github.com/TabooLib/TabooLib) 仓库。  

[Taboolib文档](https://docs.tabooproject.org/)首页翻到的

**Comment by XieXiLin158** [comment]
> 服务器插件列表:
> 
> ```
> > plugins
> [19:55:11 INFO]: Plugins (20): AuthMe, floodgate, FloodgatePlaceholders, Geyser-Spigot, JukeBox, LuckPerms, Multiverse-Core, Multiverse-Portals, NoteBlockAPI, PlaceholderAPI, ProtocolLib, Slimefun, Terra, Themis, UltiCore, UltiEconomy, UltimateTimber, UltiTools, Vault, WorldEdit
> ```
> 
> 而且我看Taboolib那边说
> 
> TabooLib 自 `6.0` 版本起不再是 动态下载 模式，而是改为由依赖插件自行打包并随本体同时载入的纯类库形式。这极大程度的提升了插件的稳定性和安全性，正因如此 TabooLib 的所有工具也在这个版本进行了全面重新设计。整个库被拆分为数个模块，由这些模块共同组成 TabooLib 6.0，你可以在 [这里](https://docs.tabooproject.org/about/structure.html) 了解模块之间的结构与相关信息，或直接访问我们的 [Github](https://github.com/TabooLib/TabooLib) 仓库。
> 
> [Taboolib文档](https://docs.tabooproject.org/)首页翻到的

`1.17.1` Paperspigot`目前没问题（ 有可能是该端还不能运作插件（ [净瞎说可能]

**Comment by XieXiLin158** [comment]
不过 `DependencyDownloader.download` 问题我也是第一次见

**Comment by AlexXuCN** [comment]
> `1.17.1 Paperspigot`目前没问题（ 有可能是该端还不能运作插件（ [净瞎说可能]

话说我这不也是paper的fork吗，就是套娃的层数多了点（（（

**Comment by Itsusinn** [comment]
=-=
不再使用taboolib
